version: "3"

networks:
  newsbotDev:
    external: true
    

services:
  api:
    image: ghcr.io/jtom38/newsbotapi:master
    environment:
      - NEWSBOT_DATABASE_NAME = 'newsbot.api'
      - NEWSBOT_DATABASE_TYPE = 'sqlite'
      - NEWSBOT_DATABASE_PATH = '/'
    ports:
      - 8000:8000
    networks:
      - newsbotDev

  worker:
    image: ghcr.io/jtom38/newsbot.worker:master
    env_file:
      - ./.env
    shm_size: 3gb
    networks:
      - newsbotDev
    depends_on: 
      - api


