version: '3'

networks:
  newsbotDev:
    external: true

services:
  app:
    build: 
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        VARIANT: 3
        USER_UID: 1000
        USER_GID: 1000
    # Needed for selenium
    shm_size: 3gb
    volumes:
      - ..:/workspace:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:db

    # networks: 
    #  - newsbotDev

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    #networks:
    #  invmon:
    ports:
      - 5432:5432

  monitor:
    image: pyroscope/pyroscope:latest
    ports:
      - 4040:4040
    command:
      - "server"

volumes:
  postgres-data: null