name: Python Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: flake8 API
        run: flake8 --ignore E501,F401,F405 ./workerApi ./workerInfra ./workerService
