name: Python Lint

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install flake8
        run: pip install flake8

      - name: flake8 API
        run: flake8 --ignore E501,F401,F405 ./workerApi

      - name: flake8 Infra
        run: flake8 --ignore E501,F401,F405 ./workerInfra

      - name: flake8 Service
        run: flake8 --ignore E501,F401,F405 ./workerService
